In [ ]:
!pip install "camelot-py[cv]" -q

     |████████████████████████████████| 40 kB 23 kB/s
     |████████████████████████████████| 77 kB 3.5 MB/s
     |████████████████████████████████| 5.6 MB 32.0 MB/s
     |████████████████████████████████| 11.7 MB 28.8 MB/s
     |████████████████████████████████| 3.6 MB 57.7 MB/s
  Building wheel for PyPDF2 (setup.py) ... done

In [ ]:
!apt-get install ghostscript

Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  fonts-droid-fallback fonts-noto-mono gsfonts libcupsfilters1 libcupsimage2
  libgs9 libgs9-common libijs-0.35 libjbig2dec0 poppler-data
Suggested packages:
  fonts-noto ghostscript-x poppler-utils fonts-japanese-mincho
  | fonts-ipafont-mincho fonts-japanese-gothic | fonts-ipafont-gothic
  fonts-arphic-ukai fonts-arphic-uming fonts-nanum
The following NEW packages will be installed:
  fonts-droid-fallback fonts-noto-mono ghostscript gsfonts libcupsfilters1
  libcupsimage2 libgs9 libgs9-common libijs-0.35 libjbig2dec0 poppler-data
0 upgraded, 11 newly installed, 0 to remove and 37 not upgraded.
Need to get 14.1 MB of archives.
After this operation, 49.9 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 fonts-droid-fallback all 1:6.0.1r16-1.1 [1,805 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic/main amd64 poppler-data all 0.4.8-2 [1,479 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic/main amd64 fonts-noto-mono all 20171026-2 [75.5 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libcupsimage2 amd64 2.2.7-1ubuntu2.8 [18.6 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/main amd64 libijs-0.35 amd64 0.35-13 [15.5 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic/main amd64 libjbig2dec0 amd64 0.13-6 [55.9 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libgs9-common all 9.26~dfsg+0-0ubuntu0.18.04.14 [5,092 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libgs9 amd64 9.26~dfsg+0-0ubuntu0.18.04.14 [2,265 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 ghostscript amd64 9.26~dfsg+0-0ubuntu0.18.04.14 [51.3 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic/main amd64 gsfonts all 1:8.11+urwcyr1.0.7~pre44-4.4 [3,120 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libcupsfilters1 amd64 1.20.2-0ubuntu3.1 [108 kB]
Fetched 14.1 MB in 2s (6,710 kB/s)
Selecting previously unselected package fonts-droid-fallback.
(Reading database ... 155225 files and directories currently installed.)
Preparing to unpack .../00-fonts-droid-fallback_1%3a6.0.1r16-1.1_all.deb ...
Unpacking fonts-droid-fallback (1:6.0.1r16-1.1) ...
Selecting previously unselected package poppler-data.
Preparing to unpack .../01-poppler-data_0.4.8-2_all.deb ...
Unpacking poppler-data (0.4.8-2) ...
Selecting previously unselected package fonts-noto-mono.
Preparing to unpack .../02-fonts-noto-mono_20171026-2_all.deb ...
Unpacking fonts-noto-mono (20171026-2) ...
Selecting previously unselected package libcupsimage2:amd64.
Preparing to unpack .../03-libcupsimage2_2.2.7-1ubuntu2.8_amd64.deb ...
Unpacking libcupsimage2:amd64 (2.2.7-1ubuntu2.8) ...
Selecting previously unselected package libijs-0.35:amd64.
Preparing to unpack .../04-libijs-0.35_0.35-13_amd64.deb ...
Unpacking libijs-0.35:amd64 (0.35-13) ...
Selecting previously unselected package libjbig2dec0:amd64.
Preparing to unpack .../05-libjbig2dec0_0.13-6_amd64.deb ...
Unpacking libjbig2dec0:amd64 (0.13-6) ...
Selecting previously unselected package libgs9-common.
Preparing to unpack .../06-libgs9-common_9.26~dfsg+0-0ubuntu0.18.04.14_all.deb ...
Unpacking libgs9-common (9.26~dfsg+0-0ubuntu0.18.04.14) ...
Selecting previously unselected package libgs9:amd64.
Preparing to unpack .../07-libgs9_9.26~dfsg+0-0ubuntu0.18.04.14_amd64.deb ...
Unpacking libgs9:amd64 (9.26~dfsg+0-0ubuntu0.18.04.14) ...
Selecting previously unselected package ghostscript.
Preparing to unpack .../08-ghostscript_9.26~dfsg+0-0ubuntu0.18.04.14_amd64.deb ...
Unpacking ghostscript (9.26~dfsg+0-0ubuntu0.18.04.14) ...
Selecting previously unselected package gsfonts.
Preparing to unpack .../09-gsfonts_1%3a8.11+urwcyr1.0.7~pre44-4.4_all.deb ...
Unpacking gsfonts (1:8.11+urwcyr1.0.7~pre44-4.4) ...
Selecting previously unselected package libcupsfilters1:amd64.
Preparing to unpack .../10-libcupsfilters1_1.20.2-0ubuntu3.1_amd64.deb ...
Unpacking libcupsfilters1:amd64 (1.20.2-0ubuntu3.1) ...
Setting up libgs9-common (9.26~dfsg+0-0ubuntu0.18.04.14) ...
Setting up fonts-droid-fallback (1:6.0.1r16-1.1) ...
Setting up gsfonts (1:8.11+urwcyr1.0.7~pre44-4.4) ...
Setting up poppler-data (0.4.8-2) ...
Setting up fonts-noto-mono (20171026-2) ...
Setting up libcupsfilters1:amd64 (1.20.2-0ubuntu3.1) ...
Setting up libcupsimage2:amd64 (2.2.7-1ubuntu2.8) ...
Setting up libjbig2dec0:amd64 (0.13-6) ...
Setting up libijs-0.35:amd64 (0.35-13) ...
Setting up libgs9:amd64 (9.26~dfsg+0-0ubuntu0.18.04.14) ...
Setting up ghostscript (9.26~dfsg+0-0ubuntu0.18.04.14) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for fontconfig (2.12.6-0ubuntu2) ...
Processing triggers for libc-bin (2.27-3ubuntu1.3) ...
/sbin/ldconfig.real: /usr/local/lib/python3.7/dist-packages/ideep4py/lib/libmkldnn.so.0 is not a symbolic link

In [ ]:
import camelot as cm
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [ ]:
tables[0].df.to_excel("base1.xlsx")

In [ ]:
tables = cm.read_pdf("base_datos_notas.pdf", pages = "3", flavor = "lattice", backend="ghostscript", strip_text=' .\n')

In [ ]:
tables[0].df

                                                   0   ...                                                 16
0   REGISTRODEACTADEEVALUACIÓNEDUCACIÓNSUPERIORTEC...  ...
1                                       NombredelIEST  ...                   CARRERA:ADMINISTRACIÓNDEEMPRESAS
2                               NúmerodeCódigomodular  ...
3                                        Departamento  ...  MENCION:PERIODOACADÉMICO:2019-IISECCIÓN:IITURN...
4                                   DireccióndelIESTP  ...
5   ResolucióndeAutorización(Tipo,númeroyfecha)RMN...  ...
6   ResolucióndeRevalidación(Tipo,númeroyfecha)RDN...  ...
7                                                  N°  ...
8                                                      ...                                      OBSERVACIONES
9                                                      ...
10                                                     ...
11                                                  1  ...
12                                                  2  ...
13                                                  3  ...
14                                                  4  ...  Recuperación=Sistemadecompensación,previsional...
15                                                  5  ...
16                                                  6  ...
17                                                  7  ...
18                                                  8  ...  Recuperación=Sistemadecompensación,previsional...
19                                                  9  ...  Recuperación=Sistemadecompensación,previsional...
20                                                 10  ...
21                                                 11  ...  Recuperación=Sistemadecompensación,previsional...
22                                                 12  ...
23                                                 13  ...  Recuperación=Sistemadecompensación,previsional...
24                                                 14  ...
25                                                 15  ...
26                                                 16  ...
27                                                 17  ...
28                                                 18  ...  Recuperación=Sistemadecompensación,previsional...
29                                                 19  ...
30                                                 20  ...

[31 rows x 17 columns]

In [ ]:
table = cm.read_pdf("base_datos_notas.pdf", pages = "3-208" , flavor = "lattice", backend="ghostscript", strip_text=' .\n')

In [ ]:
table[205].df

    0   ...                                    16
0   N°  ...                         OBSERVACIONES
1       ...
2       ...
3       ...
4       ...
5   21  ...  Recuperación=Redaccióncomercial(NSP)
6   22  ...
7   23  ...
8   24  ...         Desaprobadoen2019-I=Logística
9   25  ...         Desaprobadoen2019-I=Logística
10  26  ...
11  27  ...
12  28  ...
13  29  ...
14  30  ...
15  31  ...
16  32  ...
17  33  ...
18  34  ...
19  35  ...
20  36  ...
21  37  ...
22  38  ...
23  39  ...
24  40  ...

[25 rows x 17 columns]

In [ ]:
tables[0].df

In [ ]:
writer = pd.ExcelWriter('Educacion_base.xlsx')

for i in range(0,206):

  table[i].df.to_excel(writer, sheet_name = f'base_{ i }')

writer.save()


# Bussines managment data

In [ ]:
base = pd.ExcelWriter('Administracion_empresas.xlsx')

for i in range(1,19):

    globals()[f'data{i}'] = pd.read_excel(base, sheet_name = f'Hoja{i}')

In [ ]:
data1

         dni                              nombre  FG1  ...  period  section   shift
0   74945266          AMASIFUENCALIXTOErikRusber   16  ...  2019-2        2  diurno
1   77669026              ARIASMILLAXiomaraPaola   14  ...  2019-2        2  diurno
2   74089055          ARMASCARIJANOLeonelNicolas   15  ...  2019-2        2  diurno
3   74807392        BOGGIANOPIÑANAshileeJennifer   16  ...  2019-2        2  diurno
4   71838626      CARRANZAMOSQUEIRAAnibeShandell   16  ...  2019-2        2  diurno
5   73261487       CARRASCORIVERAEmyoriluReichel   15  ...  2019-2        2  diurno
6   48124545                  CHALCOCHALQUEDavid   15  ...  2019-2        2  diurno
7   75603049                CHILESALDIVARRichard   14  ...  2019-2        2  diurno
8   75447685           COSSERCARPIOElyKatherinne   14  ...  2019-2        2  diurno
9   74842138            CUNYACRUZWilderSebastian   17  ...  2019-2        2  diurno
10  76455726  FLORESHUALLPATUEROGianellaLeonarda   15  ...  2019-2        2  diurno
11  75524366      GUTIERREZCAMARGOMichaelAnthony   16  ...  2019-2        2  diurno
12  74733420       GUZMANALBINAGORTADiegoLuciano   15  ...  2019-2        2  diurno
13  71395870           GUZMANCORTEZRosarioLeonor   17  ...  2019-2        2  diurno
14  70923813        HUAMANIGALLEGOSMariadelPilar   16  ...  2019-2        2  diurno
15  76428231        HUERTAGUTIERREZCamilaLuciana   10  ...  2019-2        2  diurno
16  75198464            JARAMILLOARAPADavidAngel   15  ...  2019-2        2  diurno
17  78016923          JIMENEZCAMONESNayluYelissa   14  ...  2019-2        2  diurno
18  72819694             LATORRESORIAMelanyBrisa   17  ...  2019-2        2  diurno
19  60797274              LEONROMAINAAlissonRubi   16  ...  2019-2        2  diurno

[20 rows x 16 columns]

In [ ]:
base_final = data1.append(data2, ignore_index=True)

for i in range(3,19):

    base_final = base_final.append(globals()[f'data{i}'], ignore_index=True)

In [ ]:
base_final

          dni                           nombre  FG1  FG2  ... FC29 FC30 FC31 FC32
0    74945266       AMASIFUENCALIXTOErikRusber   16   14  ...  NaN  NaN  NaN  NaN
1    77669026           ARIASMILLAXiomaraPaola   14   14  ...  NaN  NaN  NaN  NaN
2    74089055       ARMASCARIJANOLeonelNicolas   15   14  ...  NaN  NaN  NaN  NaN
3    74807392     BOGGIANOPIÑANAshileeJennifer   16    0  ...  NaN  NaN  NaN  NaN
4    71838626   CARRANZAMOSQUEIRAAnibeShandell   16   15  ...  NaN  NaN  NaN  NaN
..        ...                              ...  ...  ...  ...  ...  ...  ...  ...
225  76674075        CRUZPIZARROBrendaFiorella  NaN  NaN  ...   --   --   --   14
226   9692807            ALARCÓNORIHUELATeresa  NaN  NaN  ...   --   15   --   --
227  72229250  LEGUASOTOMAYORMadellinAntonella  NaN  NaN  ...   --   --   --   14
228  70884307             CANCHARIFELIXMaribel  NaN  NaN  ...  NaN  NaN  NaN  NaN
229  74616106          HUANACOCHIMAICOCarolina  NaN  NaN  ...  NaN  NaN  NaN  NaN

[230 rows x 64 columns]

In [ ]:
base_final = base_final.replace(np.nan, ".")
base_final

          dni                           nombre FG1 FG2  ... FC29 FC30 FC31 FC32
0    74945266       AMASIFUENCALIXTOErikRusber  16  14  ...    .    .    .    .
1    77669026           ARIASMILLAXiomaraPaola  14  14  ...    .    .    .    .
2    74089055       ARMASCARIJANOLeonelNicolas  15  14  ...    .    .    .    .
3    74807392     BOGGIANOPIÑANAshileeJennifer  16   0  ...    .    .    .    .
4    71838626   CARRANZAMOSQUEIRAAnibeShandell  16  15  ...    .    .    .    .
..        ...                              ...  ..  ..  ...  ...  ...  ...  ...
225  76674075        CRUZPIZARROBrendaFiorella   .   .  ...   --   --   --   14
226   9692807            ALARCÓNORIHUELATeresa   .   .  ...   --   15   --   --
227  72229250  LEGUASOTOMAYORMadellinAntonella   .   .  ...   --   --   --   14
228  70884307             CANCHARIFELIXMaribel   .   .  ...    .    .    .    .
229  74616106          HUANACOCHIMAICOCarolina   .   .  ...    .    .    .    .

[230 rows x 64 columns]

In [ ]:
cols = base_final[["pased", "disapproved", "period","section","shift"]]
cols

     pased  disapproved  period  section     shift
0        9            0  2019-2        2    diurno
1        9            0  2019-2        2    diurno
2        9            0  2019-2        2    diurno
3        8            1  2019-2        2    diurno
4        9            0  2019-2        2    diurno
..     ...          ...     ...      ...       ...
225      1            0  2019-2        5    diurno
226      1            0  2019-2        5  nocturno
227      1            0  2019-2        5  nocturno
228      1            0  2019-2        4  nocturno
229      1            0   2019-        4  nocturno

[230 rows x 5 columns]

In [ ]:
base_final = base_final.drop(["pased", "disapproved", "period","section","shift"], axis = 1)
base_final

          dni                           nombre FG1 FG2  ... FC29 FC30 FC31 FC32
0    74945266       AMASIFUENCALIXTOErikRusber  16  14  ...    .    .    .    .
1    77669026           ARIASMILLAXiomaraPaola  14  14  ...    .    .    .    .
2    74089055       ARMASCARIJANOLeonelNicolas  15  14  ...    .    .    .    .
3    74807392     BOGGIANOPIÑANAshileeJennifer  16   0  ...    .    .    .    .
4    71838626   CARRANZAMOSQUEIRAAnibeShandell  16  15  ...    .    .    .    .
..        ...                              ...  ..  ..  ...  ...  ...  ...  ...
225  76674075        CRUZPIZARROBrendaFiorella   .   .  ...   --   --   --   14
226   9692807            ALARCÓNORIHUELATeresa   .   .  ...   --   15   --   --
227  72229250  LEGUASOTOMAYORMadellinAntonella   .   .  ...   --   --   --   14
228  70884307             CANCHARIFELIXMaribel   .   .  ...    .    .    .    .
229  74616106          HUANACOCHIMAICOCarolina   .   .  ...    .    .    .    .

[230 rows x 59 columns]

In [ ]:
base_final = pd.concat([base_final, cols], axis=1)
base_final.to_csv("base_administracion.csv")

# Codes to Building data base

In [ ]:
import camelot as cm
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
import xlrd

In [ ]:
file = 'Educacion_base.xlsx'

base_inicial = xlrd.open_workbook(file, on_demand=True)
sheet_names = base_inicial.sheet_names()

sheet_names

['base_0',
 'base_1',
 'base_2',
 'base_3',
 'base_4',
 'base_5',
 'base_6',
 'base_7',
 'base_8',
 'base_9',
 'base_10',
 'base_11',
 'base_12',
 'base_14',
 'base_15',
 'base_16',
 'base_20',
 'base_22',
 'base_24',
 'base_25',
 'base_26',
 'base_27',
 'base_28',
 'base_29',
 'base_30',
 'base_31',
 'base_32',
 'base_33',
 'base_34',
 'base_35',
 'base_36',
 'base_38',
 'base_39',
 'base_40',
 'base_41',
 'base_42',
 'base_43',
 'base_44',
 'base_45',
 'base_46',
 'base_47',
 'base_48',
 'base_49',
 'base_50',
 'base_52',
 'base_53',
 'base_54',
 'base_55',
 'base_56',
 'base_57',
 'base_58',
 'base_59',
 'base_60',
 'base_62',
 'base_63',
 'base_64',
 'base_66',
 'base_68',
 'base_70',
 'base_72',
 'base_74',
 'base_76',
 'base_78',
 'base_80',
 'base_82',
 'base_84',
 'base_86',
 'base_87',
 'base_88',
 'base_90',
 'base_91',
 'base_92',
 'base_93',
 'base_94',
 'base_96',
 'base_98',
 'base_100',
 'base_101',
 'base_102',
 'base_104',
 'base_106',
 'base_108',
 'base_109',
 'base_110',
 'base_112',
 'base_113',
 'base_114',
 'base_115',
 'base_116',
 'base_117',
 'base_118',
 'base_119',
 'base_120',
 'base_122',
 'base_123',
 'base_124',
 'base_125',
 'base_126',
 'base_127',
 'base_128',
 'base_129',
 'base_130',
 'base_131',
 'base_132',
 'base_133',
 'base_134',
 'base_135',
 'base_136',
 'base_137',
 'base_138',
 'base_139',
 'base_140',
 'base_141',
 'base_142',
 'base_143',
 'base_144',
 'base_145',
 'base_146',
 'base_147',
 'base_148',
 'base_150',
 'base_151',
 'base_152',
 'base_153',
 'base_154',
 'base_155',
 'base_156',
 'base_157',
 'base_158',
 'base_159',
 'base_160',
 'base_161',
 'base_162',
 'base_163',
 'base_164',
 'base_165',
 'base_166',
 'base_167',
 'base_168',
 'base_169',
 'base_170',
 'base_171',
 'base_172',
 'base_173',
 'base_174',
 'base_175',
 'base_176',
 'base_177',
 'base_178',
 'base_179',
 'base_180',
 'base_181',
 'base_182',
 'base_184',
 'base_185',
 'base_186',
 'base_187',
 'base_188',
 'base_189',
 'base_190',
 'base_191',
 'base_192',
 'base_194',
 'base_195',
 'base_196',
 'base_197',
 'base_198',
 'base_199',
 'base_200',
 'base_202',
 'base_203',
 'base_204',
 'base_205']

In [ ]:
base = pd.ExcelWriter('Educacion_base.xlsx')

for name in sheet_names:
 
    globals()[f'data_{name}'] = pd.read_excel(base, sheet_name= f'{name}')

In [ ]:
base_tipo_1 = data_base_0.copy()
base_tipo_2 = data_base_1.copy()

In [ ]:
base_tipo_1

     A  ... Unnamed: 19
0    0  ...         NaN
1    1  ...         NaN
2    2  ...         NaN
3    3  ...         NaN
4    4  ...         NaN
5    5  ...         NaN
6    6  ...         NaN
7    7  ...         NaN
8    8  ...         NaN
9    9  ...        comp
10  10  ...        192d
11  11  ...        192d
12  12  ...         NaN
13  13  ...         NaN
14  14  ...         NaN
15  15  ...         NaN
16  16  ...         NaN
17  17  ...         NaN
18  18  ...         NaN
19  19  ...         NaN
20  20  ...         NaN
21  21  ...         NaN
22  22  ...         NaN
23  23  ...         NaN
24  24  ...         NaN
25  25  ...         NaN
26  26  ...         NaN
27  27  ...         NaN
28  28  ...         NaN
29  29  ...         NaN
30  30  ...         NaN

[31 rows x 20 columns]

In [ ]:
#base = pd.ExcelWriter('Educacion_base.xlsx')

#for i in range(1,19):

    #globals()[f'data{i}'] = pd.read_excel(base, sheet_name = f'Hoja{i}')

In [ ]:
if base_tipo_1.iloc[0,1] == "REGISTRODEACTADEEVALUACIÓNEDUCACIÓNSUPERIORTECNOLÓGICAAÑO2019-PERIODOLECTIVO2019-II":
  print("arriba")
  base_tipo_1 = base_tipo_1.iloc[9:]

arriba

In [ ]:
base_tipo_1 = base_tipo_1.drop(base_tipo_1.columns[0:2], axis = 1)
base_tipo_1 = base_tipo_1.drop(labels=10, axis = 0)

In [ ]:
base_tipo_1[1][9] = "dni"
base_tipo_1[2][9] = "nombre"

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
a = base_tipo_1.iloc[1,-1]
b = base_tipo_1.iloc[1,-2]

print(a)

192d

In [ ]:
base_tipo_1 = base_tipo_1.dropna(how='all', axis = 1)

In [ ]:
base_tipo_1.iloc[:, -2] = base_tipo_1.iloc[:, -2].fillna(b, inplace=False)
base_tipo_1.iloc[:, -1] = base_tipo_1.iloc[:, -1].fillna(a, inplace=False)

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1781: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item_labels[indexer[info_axis]]] = value

In [ ]:
base_tipo_1 = base_tipo_1.rename(columns=base_tipo_1.iloc[0])
base_tipo_1 = base_tipo_1.iloc[1:]
base_tipo_1 = base_tipo_1.drop( ['obs'] , axis=1)

In [ ]:
base_tipo_1

         dni                              nombre FC21  ... disapproved ccspec  comp
11  74945266          AMASIFUENCALIXTOErikRusber   16  ...           0    100  192d
12  77669026              ARIASMILLAXiomaraPaola   14  ...           0    100  192d
13  74089055          ARMASCARIJANOLeonelNicolas   15  ...           0    100  192d
14  74807392        BOGGIANOPIÑANAshileeJennifer   16  ...           1    100  192d
15  71838626      CARRANZAMOSQUEIRAAnibeShandell   16  ...           0    100  192d
16  73261487       CARRASCORIVERAEmyoriluReichel   15  ...           0    100  192d
17  48124545                  CHALCOCHALQUEDavid   15  ...           0    100  192d
18  75603049                CHILESALDIVARRichard   14  ...           1    100  192d
19  75447685           COSSERCARPIOElyKatherinne   14  ...           1    100  192d
20  74842138            CUNYACRUZWilderSebastian   17  ...           0    100  192d
21  76455726  FLORESHUALLPATUEROGianellaLeonarda   15  ...           1    100  192d
22  75524366      GUTIERREZCAMARGOMichaelAnthony   16  ...           0    100  192d
23  74733420       GUZMANALBINAGORTADiegoLuciano   15  ...           1    100  192d
24  71395870           GUZMANCORTEZRosarioLeonor   17  ...           0    100  192d
25  70923813        HUAMANIGALLEGOSMariadelPilar   16  ...           1    100  192d
26  76428231        HUERTAGUTIERREZCamilaLuciana   10  ...           8    100  192d
27  75198464            JARAMILLOARAPADavidAngel   15  ...           0    100  192d
28  78016923          JIMENEZCAMONESNayluYelissa   14  ...           0    100  192d
29  72819694             LATORRESORIAMelanyBrisa   17  ...           0    100  192d
30  60797274              LEONROMAINAAlissonRubi   16  ...           0    100  192d

[20 rows x 15 columns]

In [ ]:
base_tipo_1

         dni                              nombre FC21  ... disapproved ccspec  comp
11  74945266          AMASIFUENCALIXTOErikRusber   16  ...           0    100  192d
12  77669026              ARIASMILLAXiomaraPaola   14  ...           0    100  192d
13  74089055          ARMASCARIJANOLeonelNicolas   15  ...           0    100  192d
14  74807392        BOGGIANOPIÑANAshileeJennifer   16  ...           1    100  192d
15  71838626      CARRANZAMOSQUEIRAAnibeShandell   16  ...           0    100  192d
16  73261487       CARRASCORIVERAEmyoriluReichel   15  ...           0    100  192d
17  48124545                  CHALCOCHALQUEDavid   15  ...           0    100  192d
18  75603049                CHILESALDIVARRichard   14  ...           1    100  192d
19  75447685           COSSERCARPIOElyKatherinne   14  ...           1    100  192d
20  74842138            CUNYACRUZWilderSebastian   17  ...           0    100  192d
21  76455726  FLORESHUALLPATUEROGianellaLeonarda   15  ...           1    100  192d
22  75524366      GUTIERREZCAMARGOMichaelAnthony   16  ...           0    100  192d
23  74733420       GUZMANALBINAGORTADiegoLuciano   15  ...           1    100  192d
24  71395870           GUZMANCORTEZRosarioLeonor   17  ...           0    100  192d
25  70923813        HUAMANIGALLEGOSMariadelPilar   16  ...           1    100  192d
26  76428231        HUERTAGUTIERREZCamilaLuciana   10  ...           8    100  192d
27  75198464            JARAMILLOARAPADavidAngel   15  ...           0    100  192d
28  78016923          JIMENEZCAMONESNayluYelissa   14  ...           0    100  192d
29  72819694             LATORRESORIAMelanyBrisa   17  ...           0    100  192d
30  60797274              LEONROMAINAAlissonRubi   16  ...           0    100  192d

[20 rows x 15 columns]

In [ ]:
data_base_1

     B  ... Unnamed: 19
0    0  ...         NaN
1    1  ...         NaN
2    2  ...         NaN
3    3  ...        comp
4    4  ...        192d
5    5  ...        192d
6    6  ...         NaN
7    7  ...         NaN
8    8  ...         NaN
9    9  ...         NaN
10  10  ...         NaN
11  11  ...         NaN
12  12  ...         NaN
13  13  ...         NaN
14  14  ...         NaN
15  15  ...         NaN
16  16  ...         NaN
17  17  ...         NaN
18  18  ...         NaN
19  19  ...         NaN
20  20  ...         NaN
21  21  ...         NaN
22  22  ...         NaN
23  23  ...         NaN
24  24  ...         NaN
25  25  ...         NaN
26  26  ...         NaN
27  27  ...         NaN
28  28  ...         NaN
29  29  ...         NaN

[30 rows x 20 columns]

In [ ]:
if base_tipo_2.iloc[0,1] == "N°":
  print("arriba")
  base_tipo_2 = base_tipo_2.iloc[3:]

arriba

In [ ]:
base_tipo_2 = base_tipo_2.drop(base_tipo_2.columns[0:2], axis = 1)
base_tipo_2 = base_tipo_2.drop(labels=4, axis = 0)

In [ ]:
base_tipo_2[1][3] = "dni"
base_tipo_2[2][3] = "nombre"

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
a = base_tipo_1.iloc[1,-1]
b = base_tipo_1.iloc[1,-2]

print(a)

192d

In [ ]:
base_tipo_2 = base_tipo_2.dropna(how='all', axis = 1)

In [ ]:
base_tipo_2.iloc[:, -2] = base_tipo_2.iloc[:, -2].fillna(b, inplace=False)
base_tipo_2.iloc[:, -1] = base_tipo_2.iloc[:, -1].fillna(a, inplace=False)

In [ ]:
base_tipo_2 = base_tipo_2.rename(columns=base_tipo_2.iloc[0])
base_tipo_2 = base_tipo_2.iloc[1:]
base_tipo_2 = base_tipo_2.drop( ['obs'] , axis=1)

In [ ]:
base_tipo_2 = base_tipo_2.dropna()

In [ ]:
base_tipo_2

         dni                             nombre FC21  ... disapproved ccspec  comp
5   70464097               LOPEZVARGASJuanDiego   15  ...           0    100  192d
6   76358893             MALLQUISAICOFavioRonal   15  ...           0    100  192d
7   48605011           MENDOZAOBISPOLuisEnrique   15  ...           0    100  192d
8   72427894             MUÑOZPORTAElenaCecilia   16  ...           0    100  192d
9   77207847              NAVARROKOOMiguelAngel   15  ...           0    100  192d
10  48314340         PALACIOSSOTOMarisellaDaian   17  ...           0    100  192d
11  75271769        QUISPEMACAVILCALisethJanina   15  ...           0    100  192d
12  75199175          RAMIREZYUCRASergioNicolas   10  ...           7    100  192d
13  75430220                REYESNECIOSUPNicole   00  ...           9    100  192d
14  75154100  RODRIGUEZBEDREÑANAAndreaAlexandra   14  ...           1    100  192d
15  73501980       RODRIGUEZMARQUEZLucyAntuanet   14  ...           1    100  192d
16  74726938               ROJASARONIMariaElena   14  ...           1    100  192d
17  71048060                  ROJASHUAYANARayda   16  ...           0    100  192d
18  76592330              RUIZARCOSilvanaRaquel   16  ...           0    100  192d
19  70932938        SAAVEDRAVELASQUEZEstrellita   15  ...           0    100  192d
20  71257178      ZEVALLOSORTIZMarizorMariaInes   16  ...           0    100  192d
21  45870378            TOMASTORREStellaYadhira   15  ...           0    100  192d

[17 rows x 15 columns]

## **Bucle final data**

In [ ]:
for name in sheet_names:

  if globals()[f'data_{name}'].iloc[1,1] == "NombredelIEST":
    globals()[f'data_{name}'] = globals()[f'data_{name}'].iloc[9:]

    globals()[f'data_{name}'] = globals()[f'data_{name}'].drop(globals()[f'data_{name}'].columns[0:2], axis = 1)
    
    globals()[f'data_{name}'][1][9] = "dni"
    globals()[f'data_{name}'][2][9] = "nombre"

    a = globals()[f'data_{name}'].iloc[1,-1]
    b = globals()[f'data_{name}'].iloc[1,-2]  

    globals()[f'data_{name}'] = globals()[f'data_{name}'].dropna(how='all', axis = 1)

    globals()[f'data_{name}'].iloc[:, -2] = globals()[f'data_{name}'].iloc[:, -2].fillna(b, inplace=False)
    globals()[f'data_{name}'].iloc[:, -1] = globals()[f'data_{name}'].iloc[:, -1].fillna(a, inplace=False)

    globals()[f'data_{name}'] = globals()[f'data_{name}'].drop(labels=10, axis = 0) 

    globals()[f'data_{name}'] = globals()[f'data_{name}'].rename(columns=globals()[f'data_{name}'].iloc[0])
    globals()[f'data_{name}'] = globals()[f'data_{name}'].iloc[1:]
    globals()[f'data_{name}'] = globals()[f'data_{name}'].drop(['obs'] , axis = 1) 

    globals()[f'data_{name}'] = globals()[f'data_{name}'].dropna() 

  elif  globals()[f'data_{name}'].iloc[0,1] == "N°":
      globals()[f'data_{name}'] =  globals()[f'data_{name}'].iloc[3:]

      globals()[f'data_{name}'] = globals()[f'data_{name}'].drop(globals()[f'data_{name}'].columns[0:2], axis = 1)
      
      globals()[f'data_{name}'][1][3] = "dni"
      globals()[f'data_{name}'][2][3] = "nombre"

      a = globals()[f'data_{name}'].iloc[1,-1]
      b = globals()[f'data_{name}'].iloc[1,-2]

      globals()[f'data_{name}'] = globals()[f'data_{name}'].dropna(how='all', axis = 1)

      globals()[f'data_{name}'].iloc[:, -2] = globals()[f'data_{name}'].iloc[:, -2].fillna(b, inplace=False)
      globals()[f'data_{name}'].iloc[:, -1] = globals()[f'data_{name}'].iloc[:, -1].fillna(a, inplace=False)

      globals()[f'data_{name}'] = globals()[f'data_{name}'].drop(labels=4, axis = 0)

      globals()[f'data_{name}'] = globals()[f'data_{name}'].rename(columns=globals()[f'data_{name}'].iloc[0])
      globals()[f'data_{name}'] = globals()[f'data_{name}'].iloc[1:]
      globals()[f'data_{name}'] = globals()[f'data_{name}'].drop(['obs'] , axis = 1)  

      globals()[f'data_{name}'] = globals()[f'data_{name}'].dropna()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1781: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item_labels[indexer[info_axis]]] = value
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame


In [ ]:
data_base_0

         dni                              nombre GC1  ... disapproved ccspec  comp
11  74945266          AMASIFUENCALIXTOErikRusber  16  ...           0    100  192d
12  77669026              ARIASMILLAXiomaraPaola  14  ...           0    100  192d
13  74089055          ARMASCARIJANOLeonelNicolas  15  ...           0    100  192d
14  74807392        BOGGIANOPIÑANAshileeJennifer  16  ...           1    100  192d
15  71838626      CARRANZAMOSQUEIRAAnibeShandell  16  ...           0    100  192d
16  73261487       CARRASCORIVERAEmyoriluReichel  15  ...           0    100  192d
17  48124545                  CHALCOCHALQUEDavid  15  ...           0    100  192d
18  75603049                CHILESALDIVARRichard  14  ...           1    100  192d
19  75447685           COSSERCARPIOElyKatherinne  14  ...           1    100  192d
20  74842138            CUNYACRUZWilderSebastian  17  ...           0    100  192d
21  76455726  FLORESHUALLPATUEROGianellaLeonarda  15  ...           1    100  192d
22  75524366      GUTIERREZCAMARGOMichaelAnthony  16  ...           0    100  192d
23  74733420       GUZMANALBINAGORTADiegoLuciano  15  ...           1    100  192d
24  71395870           GUZMANCORTEZRosarioLeonor  17  ...           0    100  192d
25  70923813        HUAMANIGALLEGOSMariadelPilar  16  ...           1    100  192d
26  76428231        HUERTAGUTIERREZCamilaLuciana  10  ...           8    100  192d
27  75198464            JARAMILLOARAPADavidAngel  15  ...           0    100  192d
28  78016923          JIMENEZCAMONESNayluYelissa  14  ...           0    100  192d
29  72819694             LATORRESORIAMelanyBrisa  17  ...           0    100  192d
30  60797274              LEONROMAINAAlissonRubi  16  ...           0    100  192d

[20 rows x 15 columns]

In [ ]:
data_base_100

         dni                          nombre GC1  ... disapproved ccspec  comp
11  76332206     ALDERETEHUAMANCHARoggerYuri  17  ...           1    600  192n
12  76809041  ALDERETEHUAMANCHAYoelAlejandro  14  ...           0    600  192n
13  70171115        BRAVOCONDORJeremyAnthony  15  ...           0    600  192n
14  47647928             CHILENOQUINTOAlexis  18  ...           0    600  192n
15  75326256          DAVILABALLONKhaledOmar  18  ...           0    600  192n
16  48280601       GARCIAJIMENEZArnoldRobert  15  ...           0    600  192n
17  75270641      GONZALESCANTORINBorisBruce  13  ...           4    600  192n
18  73798038                LOPECHARAAlfredo  16  ...           0    600  192n
19  47306420          LOZANORUIZDiegoArmando  16  ...           0    600  192n
20  77709926        MAYTABARZOLAMiunserNiger  14  ...           0    600  192n
21  74094144       MELENDEZMELENDEZGuillermo  18  ...           0    600  192n
22  45173971             MEZAALATALazaroLuis  16  ...           0    600  192n
23  73621349     MONTENEGROBLASCarlosEduardo  00  ...          10    600  192n
24  70935451        ORTIZMENDIVILCarlosJesus  17  ...           2    600  192n
25  70547796                PALOMINOZEARonal  00  ...          10    600  192n
26  75281790     RAMIREZRIVASCristiamJhunior  15  ...           0    600  192n
27  72746294      RIVERAGUTIERREZIvanEduardo  15  ...           0    600  192n
28  74754492      SAMANIEGOTIRADOAlanGustavo  14  ...           0    600  192n
29  73980033        SILVERAIÑIGOAbnerAbraham  13  ...           0    600  192n
30  74307944         SOTOGONZALESJhonAnthony  13  ...           1    600  192n

[20 rows x 16 columns]

In [ ]:
data_base_204

         dni                            nombre GC24  ... disapproved ccspec  comp
11  71804453       ACEVEDOMARQUINAJulisaRosita   16  ...           1    700  205n
12  73980064          AGUILARROJASKarolXibelli   18  ...           0    700  205n
13  77463621        ARQUECAHUASCANCOMariaEliza   00  ...           9    700  205n
14  75199304           BRIOSORONQUILLOAdelinda   00  ...           7    700  205n
15  70521281             CANREACCOMelaniaErika   16  ...           1    700  205n
16  76304578  CARBAJALGALARZAFranccescaMiluska   18  ...           0    700  205n
17  70977028          CHAVEZBELTRANMonicaDiana   16  ...           0    700  205n
18  74710787               CRUZARISTAJacquelin   18  ...           0    700  205n
19  74434035         DOMINGUEZSAAVEDRALuzMaria   00  ...          10    700  205n
20  44454663    DURANDDURANDGuianellaGuadalupe   16  ...           0    700  205n
21  72610459      ELORREAGADIAZOlenkaMagdalena   15  ...           0    700  205n
22  76784794    LINARESHUARCAYAKeysyDelRosario   16  ...           0    700  205n
23  70027373        MACEDORAMOSVanessaMarjorie   17  ...           0    700  205n
24  75272386      MOLINACUEVAKatherineeMelissa   18  ...           0    700  205n
25  74765938                   OJEDAOJEDABetzy   17  ...           0    700  205n
26  70892957         ORDONIOURIOLYesicaLiliana   16  ...           1    700  205n
27  73188193   PAULINOIPANAQUEJesseniaBrillith   15  ...           1    700  205n
28  73980419      RUIZGABRIELRosariodelMilagro   17  ...           0    700  205n
29  75414612     SANTIAGOSERNAQUEDaianaCeleste   16  ...           1    700  205n
30  10235181         SOLANOLABIOLourdesMaritza   17  ...           0    700  205n

[20 rows x 16 columns]

In [ ]:
base_completa = data_base_0.copy()
sheet_names1 = sheet_names[1:]

In [ ]:
for name in sheet_names1:

  base_completa = base_completa.append(globals()[f'data_{name}'], ignore_index=True)

In [ ]:
cols = base_completa[["pased", "disapproved", "ccspec","comp"]]

In [ ]:
print(cols)

     pased disapproved ccspec  comp
0        9           0    100  192d
1        9           0    100  192d
2        9           0    100  192d
3        8           1    100  192d
4        9           0    100  192d
...    ...         ...    ...   ...
3097     9           1    700  205n
3098     9           1    700  205n
3099     9           1    700  205n
3100     1           0    700  205n
3101     1           0    700  205n

[3102 rows x 4 columns]

In [ ]:
base_completa = base_completa.drop(["nombre","pased", "disapproved", "ccspec","comp"], axis = 1)

In [ ]:
base_completa = pd.concat([base_completa, cols], axis=1)
base_completa

           dni  GC1  GC2  GC3  GC4  ... FC119 pased disapproved ccspec  comp
0     74945266   16   14   16   18  ...   NaN     9           0    100  192d
1     77669026   14   14   15   17  ...   NaN     9           0    100  192d
2     74089055   15   14   15   19  ...   NaN     9           0    100  192d
3     74807392   16   00   15   16  ...   NaN     8           1    100  192d
4     71838626   16   15   16   15  ...   NaN     9           0    100  192d
...        ...  ...  ...  ...  ...  ...   ...   ...         ...    ...   ...
2387  44326402  NaN  NaN  NaN  NaN  ...   NaN     9           1    700  205n
2388  75216028  NaN  NaN  NaN  NaN  ...   NaN     9           1    700  205n
2389  73561224  NaN  NaN  NaN  NaN  ...   NaN     9           1    700  205n
2390  73875551  NaN  NaN  NaN  NaN  ...   NaN     1           0    700  205n
2391  48595279  NaN  NaN  NaN  NaN  ...   NaN     1           0    700  205n

[2392 rows x 272 columns]

In [ ]:
carrera = pd.read_excel("cursos.xlsx", sheet_name = "carrera")
complement = pd.read_excel("cursos.xlsx", sheet_name = "complemento")

In [ ]:
carrera

   ccspec                     carrera
0     100  Administracion de empresas
1     200   Computacion e informatica
2     300                Contabilidad
3     400    Electrotecnia industrial
4     500         Mecanica automotriz
5     600      Mecanica de produccion
6     700      Secretariado ejecutivo

In [ ]:
complement

    comp  period  section     shift
0   191d       1        1    diurno
1   192d       1        2    diurno
2   193d       1        3    diurno
3   194d       1        4    diurno
4   195d       1        5    diurno
5   196d       1        6    diurno
6   191n       1        1  nocturno
7   192n       1        2  nocturno
8   193n       1        3  nocturno
9   194n       1        4  nocturno
10  195n       1        5  nocturno
11  196n       1        6  nocturno
12  201d       2        1    diurno
13  202d       2        2    diurno
14  203d       2        3    diurno
15  204d       2        4    diurno
16  205d       2        5    diurno
17  206d       2        6    diurno
18  201n       2        1  nocturno
19  202n       2        2  nocturno
20  203n       2        3  nocturno
21  204n       2        4  nocturno
22  205n       2        5  nocturno
23  206n       2        6  nocturno

In [ ]:
base_completa = pd.merge(base_completa, carrera, how="left", on="ccspec")

In [ ]:
base_completa= pd.merge(base_completa, complement, how="left", on="comp")

In [ ]:
base_completa

           dni  GC1  GC2  ... period section     shift
0     74945266   16   14  ...      1       2    diurno
1     77669026   14   14  ...      1       2    diurno
2     74089055   15   14  ...      1       2    diurno
3     74807392   16   00  ...      1       2    diurno
4     71838626   16   15  ...      1       2    diurno
...        ...  ...  ...  ...    ...     ...       ...
2387  44326402  NaN  NaN  ...      2       5  nocturno
2388  75216028  NaN  NaN  ...      2       5  nocturno
2389  73561224  NaN  NaN  ...      2       5  nocturno
2390  73875551  NaN  NaN  ...      2       5  nocturno
2391  48595279  NaN  NaN  ...      2       5  nocturno

[2392 rows x 276 columns]

In [ ]:
cols = base_completa.columns.tolist()
cols

['dni',
 'GC1',
 'GC2',
 'GC3',
 'GC4',
 'GC5',
 'FC99',
 'FC100',
 'FC101',
 'FC102',
 'GC6',
 'GC7',
 'GC8',
 'FC72',
 'FC73',
 'FC74',
 'FC75',
 'GC9',
 'GC10',
 'GC11',
 'FC84',
 'FC85',
 'FC86',
 'FC87',
 'FC131',
 'FC132',
 'FC133',
 'FC31',
 'FC32',
 'FC33',
 'GC12',
 'GC13',
 'GC14',
 'GC15',
 'FC216',
 'FC61',
 'FC62',
 'FC34',
 'FC35',
 'FC36',
 'GC16',
 'GC17',
 'GC18',
 'FC213',
 'FC214',
 'FC215',
 'GC19',
 'GC20',
 'GC21',
 'GC22',
 'GC23',
 'GC24',
 'GC25',
 'GC26',
 'FC79',
 'FC80',
 'FC81',
 'FC82',
 'FC83',
 'FC88',
 'FC89',
 'FC90',
 'FC91',
 'FC92',
 'FC93',
 'FC44',
 'FC45',
 'FC46',
 'FC47',
 'FC63',
 'FC64',
 'FC65',
 'FC66',
 'GC27',
 'GC28',
 'GC30',
 'FC94',
 'FC95',
 'FC96',
 'FC97',
 'FC98',
 'FC194',
 'FC195',
 'FC196',
 'FC197',
 'FC41',
 'FC42',
 'FC43',
 'FC1',
 'FC2',
 'FC3',
 'FC4',
 'FC5',
 'FC126',
 'FC127',
 'FC128',
 'FC129',
 'FC130',
 'FC143',
 'FC144',
 'FC145',
 'FC146',
 'FC23',
 'FC24',
 'FC25',
 'FC26',
 'GC31',
 'FG8',
 'FC147',
 'FC148',
 'FC149',
 'FC150',
 'GC32',
 'GC33',
 'FC151',
 'FC152',
 'FC153',
 'FC154',
 'FC217',
 'FC218',
 'FC219',
 'FC220',
 'FC221',
 'FC222',
 'GC34',
 'FC122',
 'FC123',
 'FC124',
 'FC125',
 'GC35',
 'GC36',
 'GC37',
 'FC155',
 'FC156',
 'FC157',
 'FC158',
 'FC27',
 'FC28',
 'FC29',
 'FC30',
 'FC223',
 'FC224',
 'FC225',
 'GC38',
 'GC39',
 'GC40',
 'FC135',
 'FC136',
 'FC137',
 'FC138',
 'FC163',
 'FC164',
 'FC165',
 'FC166',
 'FC167',
 'FC168',
 'FC169',
 'FC170',
 'FC171',
 'FC172',
 'FC159',
 'FC160',
 'FC161',
 'FC162',
 'FC56',
 'FC57',
 'FC58',
 'FC59',
 'FC60',
 'FC187',
 'FC188',
 'FC189',
 'FC173',
 'FC174',
 'FC175',
 'FC176',
 'FC177',
 'FC193',
 'FC181',
 'FC182',
 'FC134',
 'FC120',
 'FC121',
 'FC203',
 'FC204',
 'FC205',
 'FC206',
 'FC207',
 'FC107',
 'FC108',
 'FC109',
 'FC110',
 'FC111',
 'FC112',
 'FC113',
 'FC11',
 'FC12',
 'FC13',
 'FC14',
 'FC15',
 'FC16',
 'FC17',
 'FC18',
 'FC19',
 'FC20',
 'FC21',
 'FC22',
 'FC103',
 'FC104',
 'FC105',
 'FC106',
 'FC76',
 'FC77',
 'FC78',
 'FC48',
 'FC49',
 'FC50',
 'FC51',
 'FC52',
 'FC67',
 'FC68',
 'FC69',
 'FC70',
 'FC71',
 'FC198',
 'FC199',
 'FC200',
 'FC201',
 'FC202',
 'FC37',
 'FC38',
 'FC39',
 'FC40',
 'FC6',
 'FC7',
 'FC8',
 'FC9',
 'FC10',
 'FC178',
 'FC179',
 'FC180',
 'FC139',
 'FC140',
 'FC141',
 'FC142',
 'FC53',
 'FC54',
 'FC55',
 'FC226',
 'FC227',
 'FC190',
 'FC191',
 'FC192',
 'FC183',
 'FC184',
 'FC185',
 'FC186',
 'FC208',
 'FC209',
 'FC210',
 'FC211',
 'FC212',
 'FC114',
 'FC115',
 'FC116',
 'FC117',
 'FC118',
 'FC119',
 'pased',
 'disapproved',
 'ccspec',
 'comp',
 'carrera',
 'period',
 'section',
 'shift']

In [ ]:
col_1 = ['dni', 'period']

del cols[273]
del cols[0]

cols

['GC1',
 'GC2',
 'GC3',
 'GC4',
 'GC5',
 'FC99',
 'FC100',
 'FC101',
 'FC102',
 'GC6',
 'GC7',
 'GC8',
 'FC72',
 'FC73',
 'FC74',
 'FC75',
 'GC9',
 'GC10',
 'GC11',
 'FC84',
 'FC85',
 'FC86',
 'FC87',
 'FC131',
 'FC132',
 'FC133',
 'FC31',
 'FC32',
 'FC33',
 'GC12',
 'GC13',
 'GC14',
 'GC15',
 'FC216',
 'FC61',
 'FC62',
 'FC34',
 'FC35',
 'FC36',
 'GC16',
 'GC17',
 'GC18',
 'FC213',
 'FC214',
 'FC215',
 'GC19',
 'GC20',
 'GC21',
 'GC22',
 'GC23',
 'GC24',
 'GC25',
 'GC26',
 'FC79',
 'FC80',
 'FC81',
 'FC82',
 'FC83',
 'FC88',
 'FC89',
 'FC90',
 'FC91',
 'FC92',
 'FC93',
 'FC44',
 'FC45',
 'FC46',
 'FC47',
 'FC63',
 'FC64',
 'FC65',
 'FC66',
 'GC27',
 'GC28',
 'GC30',
 'FC94',
 'FC95',
 'FC96',
 'FC97',
 'FC98',
 'FC194',
 'FC195',
 'FC196',
 'FC197',
 'FC41',
 'FC42',
 'FC43',
 'FC1',
 'FC2',
 'FC3',
 'FC4',
 'FC5',
 'FC126',
 'FC127',
 'FC128',
 'FC129',
 'FC130',
 'FC143',
 'FC144',
 'FC145',
 'FC146',
 'FC23',
 'FC24',
 'FC25',
 'FC26',
 'GC31',
 'FG8',
 'FC147',
 'FC148',
 'FC149',
 'FC150',
 'GC32',
 'GC33',
 'FC151',
 'FC152',
 'FC153',
 'FC154',
 'FC217',
 'FC218',
 'FC219',
 'FC220',
 'FC221',
 'FC222',
 'GC34',
 'FC122',
 'FC123',
 'FC124',
 'FC125',
 'GC35',
 'GC36',
 'GC37',
 'FC155',
 'FC156',
 'FC157',
 'FC158',
 'FC27',
 'FC28',
 'FC29',
 'FC30',
 'FC223',
 'FC224',
 'FC225',
 'GC38',
 'GC39',
 'GC40',
 'FC135',
 'FC136',
 'FC137',
 'FC138',
 'FC163',
 'FC164',
 'FC165',
 'FC166',
 'FC167',
 'FC168',
 'FC169',
 'FC170',
 'FC171',
 'FC172',
 'FC159',
 'FC160',
 'FC161',
 'FC162',
 'FC56',
 'FC57',
 'FC58',
 'FC59',
 'FC60',
 'FC187',
 'FC188',
 'FC189',
 'FC173',
 'FC174',
 'FC175',
 'FC176',
 'FC177',
 'FC193',
 'FC181',
 'FC182',
 'FC134',
 'FC120',
 'FC121',
 'FC203',
 'FC204',
 'FC205',
 'FC206',
 'FC207',
 'FC107',
 'FC108',
 'FC109',
 'FC110',
 'FC111',
 'FC112',
 'FC113',
 'FC11',
 'FC12',
 'FC13',
 'FC14',
 'FC15',
 'FC16',
 'FC17',
 'FC18',
 'FC19',
 'FC20',
 'FC21',
 'FC22',
 'FC103',
 'FC104',
 'FC105',
 'FC106',
 'FC76',
 'FC77',
 'FC78',
 'FC48',
 'FC49',
 'FC50',
 'FC51',
 'FC52',
 'FC67',
 'FC68',
 'FC69',
 'FC70',
 'FC71',
 'FC198',
 'FC199',
 'FC200',
 'FC201',
 'FC202',
 'FC37',
 'FC38',
 'FC39',
 'FC40',
 'FC6',
 'FC7',
 'FC8',
 'FC9',
 'FC10',
 'FC178',
 'FC179',
 'FC180',
 'FC139',
 'FC140',
 'FC141',
 'FC142',
 'FC53',
 'FC54',
 'FC55',
 'FC226',
 'FC227',
 'FC190',
 'FC191',
 'FC192',
 'FC183',
 'FC184',
 'FC185',
 'FC186',
 'FC208',
 'FC209',
 'FC210',
 'FC211',
 'FC212',
 'FC114',
 'FC115',
 'FC116',
 'FC117',
 'FC118',
 'FC119',
 'pased',
 'disapproved',
 'ccspec',
 'comp',
 'carrera',
 'section',
 'shift']

In [ ]:
list_columns = col_1 + cols

In [ ]:
base_completa = base_completa[list_columns]
base_completa

           dni  period  GC1  ...                     carrera section     shift
0     74945266       1   16  ...  Administracion de empresas       2    diurno
1     77669026       1   14  ...  Administracion de empresas       2    diurno
2     74089055       1   15  ...  Administracion de empresas       2    diurno
3     74807392       1   16  ...  Administracion de empresas       2    diurno
4     71838626       1   16  ...  Administracion de empresas       2    diurno
...        ...     ...  ...  ...                         ...     ...       ...
2387  44326402       2  NaN  ...      Secretariado ejecutivo       5  nocturno
2388  75216028       2  NaN  ...      Secretariado ejecutivo       5  nocturno
2389  73561224       2  NaN  ...      Secretariado ejecutivo       5  nocturno
2390  73875551       2  NaN  ...      Secretariado ejecutivo       5  nocturno
2391  48595279       2  NaN  ...      Secretariado ejecutivo       5  nocturno

[2392 rows x 276 columns]

In [ ]:
base_completa = base_completa.replace('--', None)
#base_completa = base_completa.replace('REGISTRODEACTADEEVALUACIÓNEDUCACIÓNSUPERIORTECNOLÓGICAAÑO2019-PERIODOLECTIVO2019-IIEVALUACIÓNEXTRAORDINARIA', None)

In [ ]:
base_completa.iloc[:,271:276]

     ccspec  comp                     carrera  section     shift
0       100  192d  Administracion de empresas        2    diurno
1       100  192d  Administracion de empresas        2    diurno
2       100  192d  Administracion de empresas        2    diurno
3       100  192d  Administracion de empresas        2    diurno
4       100  192d  Administracion de empresas        2    diurno
...     ...   ...                         ...      ...       ...
2387    700  205n      Secretariado ejecutivo        5  nocturno
2388    700  205n      Secretariado ejecutivo        5  nocturno
2389    700  205n      Secretariado ejecutivo        5  nocturno
2390    700  205n      Secretariado ejecutivo        5  nocturno
2391    700  205n      Secretariado ejecutivo        5  nocturno

[2392 rows x 5 columns]

In [ ]:
base_completa1 = base_completa.iloc[:,0:271].astype(float, errors = 'raise')

base_completa2 = base_completa.iloc[:,271:276]

base_completa = pd.concat([base_completa1, base_completa2], axis=1)

In [ ]:
base_completa

             dni  period   GC1  ...                     carrera  section     shift
0     74945266.0     1.0  16.0  ...  Administracion de empresas        2    diurno
1     77669026.0     1.0  14.0  ...  Administracion de empresas        2    diurno
2     74089055.0     1.0  15.0  ...  Administracion de empresas        2    diurno
3     74807392.0     1.0  16.0  ...  Administracion de empresas        2    diurno
4     71838626.0     1.0  16.0  ...  Administracion de empresas        2    diurno
...          ...     ...   ...  ...                         ...      ...       ...
2387  44326402.0     2.0   NaN  ...      Secretariado ejecutivo        5  nocturno
2388  75216028.0     2.0   NaN  ...      Secretariado ejecutivo        5  nocturno
2389  73561224.0     2.0   NaN  ...      Secretariado ejecutivo        5  nocturno
2390  73875551.0     2.0   NaN  ...      Secretariado ejecutivo        5  nocturno
2391  48595279.0     2.0   NaN  ...      Secretariado ejecutivo        5  nocturno

[2392 rows x 276 columns]

In [ ]:
base_completa = base_completa.sort_values(by=['dni', 'period'])

In [ ]:
base_completa = base_completa.replace(np.nan, ".")

In [ ]:
base_completa

             dni  period GC1  ...                     carrera section     shift
2294    940893.0     2.0   .  ...      Secretariado ejecutivo       1  nocturno
456     961093.0     1.0  16  ...                Contabilidad       2    diurno
571     961093.0     1.0   .  ...                Contabilidad       4  nocturno
1823    961093.0     2.0   .  ...                Contabilidad       5  nocturno
2179   4647843.0     2.0   .  ...      Mecanica de produccion       1    diurno
...          ...     ...  ..  ...                         ...     ...       ...
209   80287733.0     1.0   .  ...  Administracion de empresas       6  nocturno
719   80347844.0     1.0   .  ...    Electrotecnia industrial       4    diurno
1986  80347844.0     2.0   .  ...    Electrotecnia industrial       5    diurno
920   80652103.0     1.0   .  ...         Mecanica automotriz       6  nocturno
1172  90035159.0     2.0   .  ...  Administracion de empresas       1    diurno

[2392 rows x 276 columns]

In [ ]:
base_completa.to_csv("base_completa.csv")